# This file establishes the necessary resources on Azure to create a Demo Webserver using Ubuntu
# Authentication from file $HOME/.azure/credentials

- name: 02 - Create Ubuntu Server with Docker + Apps
  hosts: localhost
  connection: local
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m') }}"
  vars_files:
    - ./config.yml

  tasks:

    - name: Starting Now ... 
      debug: msg="Starting now @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"

    - name: Create Server NIC {{ NODE_NAME }}-{{ STUDENT_ID }}-int-nic0 with Security Group vlab-{{ STUDENT_ID }}-sg0
      azure_rm_networkinterface:
        location: "{{ DEFAULT_LOCATION }}"
        resource_group: "{{ RESOURCE_GROUP }}"
        security_group: "vlab-{{ STUDENT_ID }}-sg0"
        name: "{{ NODE_NAME }}-{{ STUDENT_ID }}-int-nic0"
        virtual_network: "{{ VNET1 }}"
        subnet: "{{ SUBNET_EXT }}"
        ip_configurations:
          - name: ipconfig1
            private_ip_allocation_method: Static
            private_ip_address: "{{ NODE_ADDRESS }}"
            public_ip_address_name: "{{ NODE_NAME }}-{{ STUDENT_ID }}-int-pip0"

    - name: Setting Lamp Server Public DNS Name to {{ NODE_NAME }}-{{ STUDENT_ID }}
      azure_rm_publicipaddress:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ NODE_NAME }}-{{ STUDENT_ID }}-int-pip0"
        domain_name: "{{ NODE_NAME }}-{{ STUDENT_ID }}"

    - name: Create {{ NODE_NAME }}-{{ STUDENT_ID }} Virtual Machine
      #no_log: true
      azure_rm_virtualmachine:
        location: "{{ DEFAULT_LOCATION }}"
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ NODE_NAME }}-{{ STUDENT_ID }}"
        vm_size: Standard_B2s
        #managed_disk_type: Standard_LRS
        managed_disk_type: Premium_LRS
        admin_username: "{{ NODE_USER }}"
        admin_password: "{{ NODE_PASSWORD }}"
        network_interfaces: "{{ NODE_NAME }}-{{ STUDENT_ID }}-int-nic0"
        append_tags: True
        tags:
          OperatingSystem: "Ubuntu"
          OperatingSystemVersion: "18.04-LTS"
          Applications: "All"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest

    - name: Run init script for docker and dependencies
      azure_rm_virtualmachineextension:
        location: "{{ DEFAULT_LOCATION }}"
        resource_group: "{{ RESOURCE_GROUP }}"
        name: server_onboarding
        virtual_machine_name: "{{ NODE_NAME }}-{{ STUDENT_ID }}"
        publisher: Microsoft.Azure.Extensions
        virtual_machine_extension_type: CustomScript
        type_handler_version: "2.0"
        #settings: '{"commandToExecute": "sudo apt-get update ; sudo apt-get install -y docker docker-compose ; sudo docker run --name hackazon --restart unless-stopped -d -p 8080:80 -p 8443:443 ianwijaya/hackazon "}'
        settings: '{"fileUris": ["https://raw.githubusercontent.com/cavalen/vlab-azure/master/files/config_server.sh"], "commandToExecute": "nohup sh config_server.sh </dev/null >/dev/null 2>&1 & "}'
        auto_upgrade_minor_version: false

    - debug: msg="- NOTE - Server is installing software in the background, It can take 8-10 min for all services to be available"

    - debug: msg="Finishing ... @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
