- name: 05 Deploy Apps using AS3
  hosts: localhost
  connection: local
  vars:
    bigipmgmtip: ""
    bigipmgmtinfo: ""
    bigipvsip: ""

  vars_files:
    - ./config.yml

  tasks:
    - name: Getting BIG-IP Mgmt Info
      azure_rm_publicipaddress_info:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ BIGIP_NAME }}-{{ STUDENT_ID }}-mgmt-pip"
      register: bigipmgmtinfo

    - name: Getting BIG-IP Mgmt Info
      set_fact:
        bigipmgmtip: "{{bigipmgmtinfo.publicipaddresses[0].ip_address }}"

    - name: MGMT IP
      debug: msg="{{bigipmgmtip}}"

    - name: Getting BIG-IP VS Private IP
      set_fact:
        bigipvsip: "{{BIGIP_ADDRESS_EXT | ipmath (1) }}"

    - name: VS Private IP
      debug: msg="{{bigipvsip}}"

    - name: AS3 POST
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        #atc_declaration_file: as3.json
        #atc_declaration_file: as3-empty.json
        atc_declaration: "{{ lookup('template', 'as3.tmpl.json') }}"
        #atc_declaration_url: "https://testurl/as3.json"
        atc_delay: 10
        atc_retries: 5
        provider:
          user: "{{ ADMINUSERNAME }}"
          password: "{{ ADMINPASSWORD }}"
          server: "{{ bigipmgmtip }}"
          validate_certs: no
          server_port: 443
          timeout: 60
          auth_provider: tmos

    # atc_AS3_status, atc_DO_status , atc_TS_status
    - debug: var=atc_AS3_status

#    Deprecated 
#    - name: Deploying AS3 configuration
#      bigip_appsvcs_extension:
#        content: "{{ lookup('file', '{{ playbook_dir }}/as3.json') }}"
#        #content: "{{ lookup('file', '{{ playbook_dir }}/as3-empty.json') }}"
#        state: present
#        provider: "{{ provider }}"